name: Build dev. 

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradle binary executable
      run: chmod +x ./gradlew
    - name: Clean
      run: ./gradlew clean
    - name: Build
      run: ./gradlew build
    - name: Build APK (dev)
      run: ./gradlew assembleDebug 
      env:
        APP_FOLDER: app
        RELEASE_TITLE: Dev. built
    - name: Rename APKs   
      run: |
        mv app/build/outputs/apk/debug/app-debug.apk campdf-$GITHUB_RUN_NUMBER-debug.apk
    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: campdf-${{ github.run_number }}-debug.apk
        path: campdf-${{ github.run_number }}-debug.apk
