name: Build dev. 

on:
 push:
  branches:
   - master
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make gradle binary executable
      run: chmod +x ./gradlew
    - name: Clean
      run: ./gradlew clean
    - name: Build
      run: ./gradlew build
    - name: Build APK (dev)
      run: ./gradlew assembleDebug 
      env:
        APP_FOLDER: app
        RELEASE_TITLE: Dev. build
    - name: Rename universal APK
      run: |
        mv app/build/outputs/apk/debug/app-universal-debug.apk campdf-universal-$GITHUB_RUN_NUMBER-debug.apk
    - name: Rename ARM64v8a APK
      run: |
        mv app/build/outputs/apk/debug/app-arm64-v8a-debug.apk campdf-arm64-v8a-$GITHUB_RUN_NUMBER-debug.apk
    - name: Upload Universal Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: campdf-universal-${{ github.run_number }}-debug.apk
        path: campdf-universal-${{ github.run_number }}-debug.apk
    - name: Upload ARM64v8a Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: campdf-arm64-v8a-${{ github.run_number }}-debug.apk
        path: campdf-arm64-v8a-${{ github.run_number }}-debug.apk
